import { cn } from "cn"

/** shadcn/ui `Skeleton` (skeleton), part of the `skeleton` primitive generated by the shadcn CLI. */
function Skeleton({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="skeleton"
      className={cn("animate-pulse rounded-md bg-muted", className)}
      {...props}
    />
  )
}

export { Skeleton }
