// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mrp.Inventory.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mrp.Inventory.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mrp.Inventory.Domain.Balance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid")
                        .HasColumnName("lot_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_balances");

                    b.HasIndex("LotId")
                        .HasDatabaseName("ix_balances_lot_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_balances_tenant_id");

                    b.HasIndex("TenantId", "WarehouseId", "ItemId")
                        .HasDatabaseName("ix_balances_tenant_id_warehouse_id_item_id");

                    b.HasIndex("TenantId", "ItemId", "LotId", "WarehouseId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_balances_tenant_id_item_id_lot_id_warehouse_id_location_id");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("TenantId", "ItemId", "LotId", "WarehouseId", "LocationId"), false);

                    b.ToTable("balances", "inventory");
                });

            modelBuilder.Entity("Mrp.Inventory.Domain.Lot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("LotNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("lot_no");

                    b.Property<DateOnly?>("MfgDate")
                        .HasColumnType("date")
                        .HasColumnName("mfg_date");

                    b.Property<string>("QcRemark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("qc_remark");

                    b.Property<string>("QcStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("qc_status");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid?>("SourceDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_document_id");

                    b.Property<string>("SupplierLot")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("supplier_lot");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_cost");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_lots");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_lots_tenant_id");

                    b.HasIndex("TenantId", "LotNo")
                        .IsUnique()
                        .HasDatabaseName("ix_lots_tenant_id_lot_no");

                    b.HasIndex("TenantId", "ItemId", "ReceivedAt")
                        .HasDatabaseName("ix_lots_tenant_id_item_id_received_at");

                    b.ToTable("lots", "inventory");
                });

            modelBuilder.Entity("Mrp.Inventory.Domain.Movement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid?>("DocumentLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_line_id");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("document_no");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("document_type");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid")
                        .HasColumnName("lot_id");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("movement_type");

                    b.Property<Guid?>("PoLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("po_line_id");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<DateOnly>("PostingDate")
                        .HasColumnType("date")
                        .HasColumnName("posting_date");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("ReversesMovementId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_movement_id");

                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Seq"));

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_cost");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_movements");

                    b.HasIndex("LotId")
                        .HasDatabaseName("ix_movements_lot_id");

                    b.HasIndex("Seq")
                        .IsUnique()
                        .HasDatabaseName("ix_movements_seq");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_movements_tenant_id");

                    b.HasIndex("TenantId", "DocumentId")
                        .HasDatabaseName("ix_movements_tenant_id_document_id");

                    b.HasIndex("TenantId", "LotId")
                        .HasDatabaseName("ix_movements_tenant_id_lot_id");

                    b.HasIndex("TenantId", "PoLineId")
                        .HasDatabaseName("ix_movements_tenant_id_po_line_id")
                        .HasFilter("po_line_id IS NOT NULL");

                    b.HasIndex("TenantId", "ItemId", "PostingDate", "Seq")
                        .HasDatabaseName("ix_movements_tenant_id_item_id_posting_date_seq");

                    b.ToTable("movements", "inventory");
                });

            modelBuilder.Entity("Mrp.Inventory.Domain.Period", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<string>("ReopenReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reopen_reason");

                    b.Property<DateTimeOffset?>("ReopenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reopened_at");

                    b.Property<Guid?>("ReopenedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reopened_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_periods");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_periods_tenant_id");

                    b.HasIndex("TenantId", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("ix_periods_tenant_id_year_month");

                    b.ToTable("periods", "inventory");
                });

            modelBuilder.Entity("Mrp.Inventory.Domain.PeriodBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid")
                        .HasColumnName("lot_id");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("value");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_period_balances");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_period_balances_tenant_id");

                    b.HasIndex("TenantId", "Year", "Month", "ItemId")
                        .HasDatabaseName("ix_period_balances_tenant_id_year_month_item_id");

                    b.ToTable("period_balances", "inventory");
                });

            modelBuilder.Entity("Mrp.Inventory.Domain.StockDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("DocumentDate")
                        .HasColumnType("date")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("document_no");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("document_type");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<Guid?>("PostedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_by");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("reference_no");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("reference_type");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("status_reason");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("ToWarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_warehouse_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset?>("VoidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_documents");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_stock_documents_tenant_id");

                    b.HasIndex("TenantId", "DocumentNo")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_documents_tenant_id_document_no");

                    b.HasIndex("TenantId", "ReferenceId")
                        .HasDatabaseName("ix_stock_documents_tenant_id_reference_id")
                        .HasFilter("reference_id IS NOT NULL");

                    b.HasIndex("TenantId", "DocumentType", "Status", "DocumentDate")
                        .HasDatabaseName("ix_stock_documents_tenant_id_document_type_status_document_date");

                    b.ToTable("stock_documents", "inventory");
                });

            modelBuilder.Entity("Mrp.Inventory.Domain.StockDocumentAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("LineId")
                        .HasColumnType("uuid")
                        .HasColumnName("line_id");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid")
                        .HasColumnName("lot_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_document_allocations");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_stock_document_allocations_document_id");

                    b.HasIndex("LineId")
                        .HasDatabaseName("ix_stock_document_allocations_line_id");

                    b.HasIndex("LotId")
                        .HasDatabaseName("ix_stock_document_allocations_lot_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_stock_document_allocations_tenant_id");

                    b.ToTable("stock_document_allocations", "inventory");
                });

            modelBuilder.Entity("Mrp.Inventory.Domain.StockDocumentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ConversionFactor")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)")
                        .HasColumnName("conversion_factor");

                    b.Property<Guid?>("CreatedLotId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_lot_id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid?>("LotId")
                        .HasColumnType("uuid")
                        .HasColumnName("lot_id");

                    b.Property<string>("LotNo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("lot_no");

                    b.Property<DateOnly?>("MfgDate")
                        .HasColumnType("date")
                        .HasColumnName("mfg_date");

                    b.Property<Guid?>("PoLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("po_line_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reason_code");

                    b.Property<string>("Remark")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("remark");

                    b.Property<decimal>("StockQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("stock_quantity");

                    b.Property<string>("SupplierLot")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("supplier_lot");

                    b.Property<decimal?>("SystemQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("system_quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("ToLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_location_id");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_cost");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_document_lines");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_stock_document_lines_tenant_id");

                    b.HasIndex("DocumentId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_document_lines_document_id_line_no");

                    b.HasIndex("TenantId", "PoLineId")
                        .HasDatabaseName("ix_stock_document_lines_tenant_id_po_line_id")
                        .HasFilter("po_line_id IS NOT NULL");

                    b.ToTable("stock_document_lines", "inventory");
                });

            modelBuilder.Entity("Mrp.Inventory.Domain.Balance", b =>
                {
                    b.HasOne("Mrp.Inventory.Domain.Lot", null)
                        .WithMany()
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_balances_lots_lot_id");
                });

            modelBuilder.Entity("Mrp.Inventory.Domain.Movement", b =>
                {
                    b.HasOne("Mrp.Inventory.Domain.Lot", null)
                        .WithMany()
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movements_lots_lot_id");
                });

            modelBuilder.Entity("Mrp.Inventory.Domain.StockDocumentAllocation", b =>
                {
                    b.HasOne("Mrp.Inventory.Domain.StockDocument", null)
                        .WithMany("Allocations")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_document_allocations_stock_documents_document_id");

                    b.HasOne("Mrp.Inventory.Domain.Lot", null)
                        .WithMany()
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_document_allocations_lots_lot_id");
                });

            modelBuilder.Entity("Mrp.Inventory.Domain.StockDocumentLine", b =>
                {
                    b.HasOne("Mrp.Inventory.Domain.StockDocument", null)
                        .WithMany("Lines")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_document_lines_stock_documents_document_id");
                });

            modelBuilder.Entity("Mrp.Inventory.Domain.StockDocument", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
