// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mrp.Production.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mrp.Production.Persistence.Migrations
{
    [DbContext(typeof(ProductionDbContext))]
    partial class ProductionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("production")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mrp.Production.Domain.BomLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BomVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("bom_version_id");

                    b.Property<Guid>("ComponentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_item_id");

                    b.Property<decimal>("ConversionFactor")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)")
                        .HasColumnName("conversion_factor");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<decimal>("LossPercent")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("loss_percent");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<string>("Remark")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("remark");

                    b.Property<decimal>("StockQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("stock_quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_bom_lines");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_bom_lines_tenant_id");

                    b.HasIndex("BomVersionId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("ix_bom_lines_bom_version_id_line_no");

                    b.HasIndex("TenantId", "ComponentItemId")
                        .HasDatabaseName("ix_bom_lines_tenant_id_component_item_id");

                    b.ToTable("bom_lines", "production");
                });

            modelBuilder.Entity("Mrp.Production.Domain.BomVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<decimal>("BatchSize")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("batch_size");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.HasKey("Id")
                        .HasName("pk_bom_versions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_bom_versions_tenant_id");

                    b.HasIndex("TenantId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_bom_versions_active_item")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("TenantId", "ItemId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("ix_bom_versions_tenant_id_item_id_version_no");

                    b.ToTable("bom_versions", "production");
                });

            modelBuilder.Entity("Mrp.Production.Domain.Demand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("reference_no");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_demands");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_demands_tenant_id");

                    b.HasIndex("TenantId", "ItemId")
                        .HasDatabaseName("ix_demands_tenant_id_item_id");

                    b.HasIndex("TenantId", "Status", "DueDate")
                        .HasDatabaseName("ix_demands_tenant_id_status_due_date");

                    b.ToTable("demands", "production");
                });

            modelBuilder.Entity("Mrp.Production.Domain.MrpRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("document_no");

                    b.Property<int>("ExceptionCount")
                        .HasColumnType("integer")
                        .HasColumnName("exception_count");

                    b.Property<int>("HorizonDays")
                        .HasColumnType("integer")
                        .HasColumnName("horizon_days");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer")
                        .HasColumnName("item_count");

                    b.Property<int>("PlannedOrderCount")
                        .HasColumnType("integer")
                        .HasColumnName("planned_order_count");

                    b.Property<Guid>("RunBy")
                        .HasColumnType("uuid")
                        .HasColumnName("run_by");

                    b.Property<DateOnly>("RunDate")
                        .HasColumnType("date")
                        .HasColumnName("run_date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_mrp_runs");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_mrp_runs_tenant_id");

                    b.HasIndex("TenantId", "DocumentNo")
                        .IsUnique()
                        .HasDatabaseName("ix_mrp_runs_tenant_id_document_no");

                    b.ToTable("mrp_runs", "production");
                });

            modelBuilder.Entity("Mrp.Production.Domain.MrpRunException", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_mrp_exceptions");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_mrp_exceptions_run_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_mrp_exceptions_tenant_id");

                    b.ToTable("mrp_exceptions", "production");
                });

            modelBuilder.Entity("Mrp.Production.Domain.MrpRunPlannedOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConvertedDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("converted_document_id");

                    b.Property<string>("ConvertedDocumentNo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("converted_document_no");

                    b.Property<string>("ConvertedDocumentType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("converted_document_type");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsLate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_late");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("order_type");

                    b.Property<string>("Pegging")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("pegging");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_mrp_planned_orders");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_mrp_planned_orders_tenant_id");

                    b.HasIndex("RunId", "Status")
                        .HasDatabaseName("ix_mrp_planned_orders_run_id_status");

                    b.ToTable("mrp_planned_orders", "production");
                });

            modelBuilder.Entity("Mrp.Production.Domain.MrpRunRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Gross")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("gross");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<decimal>("Net")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("net");

                    b.Property<decimal>("OnHand")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("on_hand");

                    b.Property<decimal>("Planned")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("planned");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<decimal>("SafetyStock")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("safety_stock");

                    b.Property<decimal>("ScheduledReceipts")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("scheduled_receipts");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_mrp_requirements");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_mrp_requirements_tenant_id");

                    b.HasIndex("RunId", "ItemId")
                        .HasDatabaseName("ix_mrp_requirements_run_id_item_id");

                    b.ToTable("mrp_requirements", "production");
                });

            modelBuilder.Entity("Mrp.Production.Domain.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BomVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("bom_version_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("DemandId")
                        .HasColumnType("uuid")
                        .HasColumnName("demand_id");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("document_no");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid?>("ParentWorkOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_work_order_id");

                    b.Property<decimal>("ProducedQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("produced_quantity");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source_reference");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StatusBeforeHold")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status_before_hold");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("status_reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_work_orders");

                    b.HasIndex("BomVersionId")
                        .HasDatabaseName("ix_work_orders_bom_version_id");

                    b.HasIndex("DemandId")
                        .HasDatabaseName("ix_work_orders_demand_id");

                    b.HasIndex("ParentWorkOrderId")
                        .HasDatabaseName("ix_work_orders_parent_work_order_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_work_orders_tenant_id");

                    b.HasIndex("TenantId", "DemandId")
                        .HasDatabaseName("ix_work_orders_tenant_id_demand_id")
                        .HasFilter("demand_id IS NOT NULL");

                    b.HasIndex("TenantId", "DocumentNo")
                        .IsUnique()
                        .HasDatabaseName("ix_work_orders_tenant_id_document_no");

                    b.HasIndex("TenantId", "ItemId")
                        .HasDatabaseName("ix_work_orders_tenant_id_item_id");

                    b.HasIndex("TenantId", "Status", "DueDate")
                        .HasDatabaseName("ix_work_orders_tenant_id_status_due_date");

                    b.ToTable("work_orders", "production");
                });

            modelBuilder.Entity("Mrp.Production.Domain.WorkOrderMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChildWorkOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_work_order_id");

                    b.Property<Guid>("ComponentItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_item_id");

                    b.Property<bool>("IsMadeInHouse")
                        .HasColumnType("boolean")
                        .HasColumnName("is_made_in_house");

                    b.Property<decimal>("IssuedQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("issued_quantity");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<decimal>("RequiredQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("required_quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id")
                        .HasName("pk_work_order_materials");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_work_order_materials_tenant_id");

                    b.HasIndex("TenantId", "ComponentItemId")
                        .HasDatabaseName("ix_work_order_materials_tenant_id_component_item_id");

                    b.HasIndex("WorkOrderId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("ix_work_order_materials_work_order_id_line_no");

                    b.ToTable("work_order_materials", "production");
                });

            modelBuilder.Entity("Mrp.Production.Domain.BomLine", b =>
                {
                    b.HasOne("Mrp.Production.Domain.BomVersion", null)
                        .WithMany("Lines")
                        .HasForeignKey("BomVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bom_lines_boms_bom_version_id");
                });

            modelBuilder.Entity("Mrp.Production.Domain.MrpRunException", b =>
                {
                    b.HasOne("Mrp.Production.Domain.MrpRun", null)
                        .WithMany("Exceptions")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mrp_exceptions_mrp_runs_run_id");
                });

            modelBuilder.Entity("Mrp.Production.Domain.MrpRunPlannedOrder", b =>
                {
                    b.HasOne("Mrp.Production.Domain.MrpRun", null)
                        .WithMany("PlannedOrders")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mrp_planned_orders_mrp_runs_run_id");
                });

            modelBuilder.Entity("Mrp.Production.Domain.MrpRunRequirement", b =>
                {
                    b.HasOne("Mrp.Production.Domain.MrpRun", null)
                        .WithMany("Requirements")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mrp_requirements_mrp_runs_run_id");
                });

            modelBuilder.Entity("Mrp.Production.Domain.WorkOrder", b =>
                {
                    b.HasOne("Mrp.Production.Domain.BomVersion", null)
                        .WithMany()
                        .HasForeignKey("BomVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_orders_bom_versions_bom_version_id");

                    b.HasOne("Mrp.Production.Domain.Demand", null)
                        .WithMany()
                        .HasForeignKey("DemandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_work_orders_demands_demand_id");

                    b.HasOne("Mrp.Production.Domain.WorkOrder", null)
                        .WithMany()
                        .HasForeignKey("ParentWorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_work_orders_work_orders_parent_work_order_id");
                });

            modelBuilder.Entity("Mrp.Production.Domain.WorkOrderMaterial", b =>
                {
                    b.HasOne("Mrp.Production.Domain.WorkOrder", null)
                        .WithMany("Materials")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_order_materials_work_orders_work_order_id");
                });

            modelBuilder.Entity("Mrp.Production.Domain.BomVersion", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Mrp.Production.Domain.MrpRun", b =>
                {
                    b.Navigation("Exceptions");

                    b.Navigation("PlannedOrders");

                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("Mrp.Production.Domain.WorkOrder", b =>
                {
                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
